{
 "title": "RabbitMQ",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rabbitmq_queue_messages,namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(rabbitmq_queue_messages{namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(queue) (rabbitmq_queue_messages{namespace=\"$namespace\", name=\"$cluster\", queue!~\"^(fatal-|retry-|delay-).*\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Fatal Queues",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(queue) (rabbitmq_queue_messages{namespace=\"$namespace\", name=\"$cluster\", queue=~\"fatal-.*\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Delay Queues",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max by(queue) (rabbitmq_queue_messages{namespace=\"$namespace\", name=\"$cluster\", queue=~\"delay-.*\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Retry Queues",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "max by(queue) (rabbitmq_queue_messages{namespace=\"$namespace\", name=\"$cluster\", queue=~\"retry-.*\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}