appendonly yes
cluster-announce-bus-port 16379
cluster-announce-port 6379
cluster-config-file /data/nodes.conf
cluster-enabled yes
cluster-migration-barrier 1
cluster-node-timeout 15000
cluster-preferred-endpoint-type hostname
cluster-require-full-coverage no
dir /data
protected-mode no