{
 "title": "__TITLE__",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(route) (increase(__REQUESTS_METRIC__[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(__BUSY_SECONDS_METRIC__[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(route, status) (increase(__RESPONSES_METRIC__[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}